# Generated by Django 3.0.1 on 2020-02-09 13:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Fullname', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('Mobile', models.CharField(max_length=15)),
                ('Password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('Room_ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Room_Image', models.ImageField(default='', upload_to='')),
                ('Room_Type', models.CharField(choices=[('Single Room', 'Single Room'), ('Double Room', 'Double Room'), ('Double Double Room', 'Double Double Room'), ('Twin Room', 'Twin Room'), ('Interconnecting Rooms', 'Interconnecting Rooms'), ('Adjoining Rooms', 'Adjoining Rooms'), ('Duplex', 'Duplex'), ('Cabana', 'Cabana'), ('Studio Room', 'Studio Room'), ('Parlor', 'Parlor'), ('Lanai', 'Lanai'), ('Efficiency Room', 'Efficiency Room'), ('Hospitality Room', 'Hospitality Room'), ('Suite Room', 'Suite Room'), ('King Bedroom', 'King Bedroom'), ('Queen Bedroom', 'Queen Bedroom')], default='', max_length=50)),
                ('Location', models.TextField(max_length=200)),
                ('Price', models.CharField(max_length=10)),
                ('Description', models.TextField(default='', max_length=5000)),
            ],
            options={
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('Booking_ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Date_of_Booking', models.DateField(default=datetime.date.today)),
                ('No_of_Rooms_Booked', models.CharField(max_length=5)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_booking_app.Customer')),
                ('Room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_booking_app.Room')),
            ],
            options={
                'db_table': 'booking',
            },
        ),
        migrations.RunSQL("INSERT INTO Room (Room_Image, Room_Type, Location, Price, Description) VALUES('Single_Room.jpg', 'Single Room', 'Hotel Yak and Yeti', '1499','You can relax and feel at home as all our single rooms are fitted with a spacious semi double bed. Some are also fitted with a desk.Room facilities include\r\nTelevision, electric hot water pot, refrigerator, dryer, table lamp, humidifier,\r\nbath, toilet, broadband connection (free), air conditioning. In room Amenities\r\nShampoo, hair rinse, body shampoo, tooth brush set, Japanese gown, towel,\r\nbath towel, slipper and a Japanese tea. The single room is fully equipped with all comforts.\r\n\r\nIn addition to the comfortable hotel lounge, the room is equipped with a Smart TV, Wi-Fi and iPod docking station. With a size of 14.5 m², our single rooms offer all the space and comfort you need during your stay in Kathmandu.')"),
        migrations.RunSQL("INSERT INTO Room (Room_Image, Room_Type, Location, Price, Description) VALUES( 'Double_Room.jpg', 'Double Room', 'Hotel Shyam Bharose', '2599','You can relax and feel at home as all our double rooms are fitted with a spacious double bed. Some are also fitted with a desk.Room facilities include\r\nTelevision, electric hot water pot, refrigerator, dryer, table lamp, humidifier,\r\nbath, toilet, broadband connection (free), air conditioning. In room Amenities\r\nShampoo, hair rinse, body shampoo, tooth brush set, Japanese gown, towel,\r\nbath towel, slipper and a Japanese tea. The double room is fully equipped with all comforts.\r\n\r\nIn addition to the comfortable hotel lounge, the room is equipped with a Smart TV, Wi-Fi and iPod docking station. With a size of 20.5 m², our double room offer all the space and comfort you need during your stay in Kathmandu.')"),
        migrations.RunSQL("INSERT INTO Room (Room_Image, Room_Type, Location, Price, Description) VALUES('Double_Double_Room.jpg', 'Double Double Room', 'Hotel Annapurna', '2999','You can relax and feel at home as all our double double rooms are fitted with a spacious two double beds. Some are also fitted with a desk.Room facilities include\r\nTelevision, electric hot water pot, refrigerator, dryer, table lamp, humidifier,\r\nbath, toilet, broadband connection (free), air conditioning. In room Amenities\r\nShampoo, hair rinse, body shampoo, tooth brush set, Japanese gown, towel,\r\nbath towel, slipper and a Japanese tea. The double double room is fully equipped with all comforts.\r\n\r\nIn addition to the comfortable hotel lounge, the room is equipped with a Smart TV, Wi-Fi and iPod docking station. With a size of 25.5 m², our rooms offer all the space and comfort you need during your stay in Kathmandu.')"),
        migrations.RunSQL("INSERT INTO Room (Room_Image, Room_Type, Location, Price, Description) VALUES('Twin_Room.jpg', 'Twin Room', 'Hotel RaniMahal', '3500','You can relax and feel at home as all our twin rooms are fitted with a spacious semi double bed. Some are also fitted with a desk.Room facilities include\r\nTelevision, electric hot water pot, refrigerator, dryer, table lamp, humidifier,\r\nbath, toilet, broadband connection (free), air conditioning. In room Amenities\r\nShampoo, hair rinse, body shampoo, tooth brush set, Japanese gown, towel,\r\nbath towel, slipper and a Japanese tea. The twin room is fully equipped with all comforts.\r\n\r\nIn addition to the comfortable hotel lounge, the room is equipped with a Smart TV, Wi-Fi and iPod docking station. With a size of 20 m², our twin rooms offer all the space and comfort you need during your stay in Kathmandu.')"),
        migrations.RunSQL("INSERT INTO Room (Room_Image, Room_Type, Location, Price, Description) VALUES('Adjoining_Room.jpg', 'Adjoining Rooms', 'Hotel Platinum', '3000','You can relax and feel at home as all our Adjoining rooms are fitted with a spacious king sized double bed. Some are also fitted with a desk.Room facilities include\r\nTelevision, electric hot water pot, refrigerator, dryer, table lamp, humidifier,\r\nbath, toilet, broadband connection (free), air conditioning. In room Amenities\r\nShampoo, hair rinse, body shampoo, tooth brush set, Japanese gown, towel,\r\nbath towel, pair of slipper and a Japanese tea. The adjoining room is fully equipped with all comforts.\r\n\r\nIn addition to the comfortable hotel lounge, the room is equipped with a Smart TV, Wi-Fi and iPod docking station. With a size of 35.5 m², our adjoining rooms offer all the space and comfort you need during your stay in Kathmandu.')"),
        migrations.RunSQL("INSERT INTO Room (Room_Image, Room_Type, Location, Price, Description) VALUES('Duplex_Room.jpg', 'Duplex', 'Hotel Blue Diamond', '4000','You can relax and feel at home as all our Duplex rooms are fitted with a spacious huge furniture. Some are also fitted with a bed.Room facilities include\r\nTelevision, electric hot water pot, refrigerator, dryer, table lamp, humidifier,\r\nbath, toilet, broadband connection (free), air conditioning. In room Amenities\r\nShampoo, hair rinse, body shampoo, tooth brush set, Japanese gown, towel,\r\nbath towel, slipper and a Japanese tea. The Duplex room is fully equipped with all comforts.\r\n\r\nIn addition to the comfortable hotel lounge, the room is equipped with a Smart TV, Wi-Fi and iPod docking station. With a size of 40 m², our duplex rooms offer all the space and comfort you need during your stay in Kathmandu.')"),
        migrations.RunSQL("INSERT INTO Room (Room_Image, Room_Type, Location, Price, Description) VALUES('Cabana_Room.jpg', 'Cabana', 'Hotel Park Village', '4500','You can relax and feel at home as all our Cabana rooms are fitted with a spacious swimming pool. Some are also fitted with a desk.Room facilities include\r\nTelevision, electric hot water pot, refrigerator, dryer, table lamp, humidifier,\r\nbath, toilet, broadband connection (free), air conditioning. In room Amenities\r\nShampoo, hair rinse, body shampoo, tooth brush set, Japanese gown, towel,\r\nbath towel, slipper and a Japanese tea. The Cabana room is fully equipped with all comforts.\r\n\r\nIn addition to the comfortable hotel lounge, the room is equipped with a Smart TV, Wi-Fi and iPod docking station. With a size of 45 m², our Cabana rooms offer all the space and comfort you need during your stay in Kathmandu.')"),
        migrations.RunSQL("INSERT INTO Room (Room_Image, Room_Type, Location, Price, Description) VALUES('Studio_Room.jpg', 'Studio Room', 'Hotel Radisson', '5500','You can relax and feel at home as all our Studio rooms are fitted with a spacious semi double bed. Some are also fitted with a desk.Room facilities include\r\nTelevision, electric hot water pot, refrigerator, dryer, table lamp, humidifier,\r\nbath, toilet, broadband connection (free), air conditioning. In room Amenities\r\nShampoo, hair rinse, body shampoo, tooth brush set, Japanese gown, towel,\r\nbath towel, slipper and a Japanese tea. The Studio room is fully equipped with all comforts.\r\n\r\nIn addition to the comfortable hotel lounge, the room is equipped with a Smart TV, Wi-Fi and iPod docking station. With a size of 40 m², our Studio rooms offer all the space and comfort you need during your stay in Kathmandu.')"),
        migrations.RunSQL("INSERT INTO Room (Room_Image, Room_Type, Location, Price, Description) VALUES('Parlor_Room.jpg', 'Parlor', 'Hotel View Kathmandu', '6500','You can relax and feel at home as all our Parlor rooms are fitted with a spacious semi double bed. Some are also fitted with a desk.Room facilities include\r\nTelevision, electric hot water pot, refrigerator, dryer, table lamp, humidifier,\r\nbath, toilet, broadband connection (free), air conditioning. In room Amenities\r\nShampoo, hair rinse, body shampoo, tooth brush set, Japanese gown, towel,\r\nbath towel, slipper and a Japanese tea. The Parlor room is fully equipped with all comforts.\r\n\r\nIn addition to the comfortable hotel lounge, the room is equipped with a Smart TV, Wi-Fi and iPod docking station. With a size of 14.5 m², our Parlor rooms offer all the space and comfort you need during your stay in Kathmandu.')")
    ]
