# Generated by Django 3.0.1 on 2020-01-19 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_booking_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Customer',
        ),
    ]
