# Generated by Django 3.0.1 on 2020-01-24 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Date_of_Booking',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
