# Generated by Django 3.0.1 on 2020-02-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Customer',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Room',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
