# Generated by Django 3.0.1 on 2020-01-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_booking_app', '0002_booking_date_of_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Customer_ID',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='Room_ID',
            field=models.IntegerField(default=False),
        ),
    ]
