# Generated by Django 3.0.1 on 2020-01-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_booking_app', '0002_remove_booking_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='Location',
            field=models.TextField(max_length=200),
        ),
    ]
