# Generated by Django 3.0.1 on 2020-02-10 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_booking_app', '0002_auto_20200209_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('no_room', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_booking_app.Customer')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_booking_app.Room')),
            ],
        ),
    ]
