# Generated by Django 3.0.1 on 2020-01-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_booking_app', '0003_auto_20200124_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Total_Price',
        ),
        migrations.AlterField(
            model_name='booking',
            name='Customer_ID',
            field=models.CharField(default=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='booking',
            name='No_of_Rooms_Booked',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Room_ID',
            field=models.CharField(default=False, max_length=5),
        ),
    ]
