# Generated by Django 3.0.1 on 2020-01-19 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_booking_app', '0003_auto_20200119_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Room',
        ),
    ]
