# Generated by Django 3.0.1 on 2020-02-10 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_booking_app', '0003_bookings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookings',
        ),
    ]
