# Generated by Django 3.0.1 on 2020-02-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_booking_app', '0004_auto_20200125_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='Description',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
